# global nutanix nodepool configs
global:
  nodepools:
    cluster: PHX-SPOC020-1
    project: BootcampInfra
    vmImage: ubuntu-22.04-server-cloudimg-amd64.img
    vmNetwork:
    - vlan2010
    vmCategories:
    - AppType=Kubernetes
    cloudInit: |-
      #cloud-config 
      package_update: true
      package_upgrade: true
      packages:
        - open-iscsi
        - nfs-common
      runcmd:
        - systemctl stop ufw && systemctl disable ufw


# Specify nodepool options. Can add multiple node groups, specify etcd, controlplane and worker roles.
nodepools:

## control plane nodepool configs
- etcd: false
  controlplane: true
  worker: false
  quantity: 1
  name: control

## etcd nodepool configs
- etcd: true
  controlplane: false
  worker: false
  quantity: 1
  name: etcd

## worker nodepool configs
- etcd: false
  controlplane: false
  worker: true
  quantity: 1
  name: worker
